spring:
  datasource:
    url: jdbc:postgresql://localhost/<%= lowerName %>
    username: postgres
    password: <%= lowerName %>123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: <%= lowerName %>-service
  profiles:
    active: dev

server:
  port: <%= port %>

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://gateway-service:8080/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
